# Client only, to use the local server, see the leximpact-server project.
version: '3.7'
services:
  leximpact_client_only:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - leximpact_net
    ports:
      - 9080:9001
    volumes:
      - .:/opt/leximpact-client
      - /opt/leximpact-client/node_modules # exclude node_modules from mount : keep it in container
      - /opt/leximpact-client/build # exclude build from mount : keep it in container

networks:
  leximpact_net:
    name: leximpact_network
