// eslint-disable-next-line no-unused-vars
import { State } from "./cas-types";

export const defaultState: State = [
  {
    lieuResidence: 0,
    name: "Foyer fiscal type",
    nbCouple: 1,
    nbEnfants: 0,
    persons: {
      childs: [],
      parents: [
        {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 1,
          invalide: 0,
          isChild: 0,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        },
      ],
    },
    revenusNetMensuel: 1300.4166666666667,
  }, {
    lieuResidence: 0,
    name: "Foyer fiscal type",
    nbCouple: 1,
    nbEnfants: 1,
    persons: {
      childs: [
        {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 0,
          invalide: 0,
          isChild: 1,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        },
      ],
      parents: [
        {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 1,
          invalide: 0,
          isChild: 0,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        },
      ],
    },
    revenusNetMensuel: 2599.5833333333335,
  }, {
    lieuResidence: 0,
    name: "Foyer fiscal type",
    nbCouple: 2,
    nbEnfants: 0,
    persons: {
      childs: [],
      parents: [
        {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 0,
          invalide: 0,
          isChild: 0,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        }, {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 1,
          invalide: 0,
          isChild: 0,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        },
      ],
    },
    revenusNetMensuel: 3200,
  }, {
    lieuResidence: 0,
    name: "Foyer fiscal type",
    nbCouple: 2,
    nbEnfants: 0,
    persons: {
      childs: [],
      parents: [
        {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 0,
          invalide: 0,
          isChild: 0,
          parentIsole: 0,
          plus65ans: 1,
          veufVeuve: 0,
        }, {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 1,
          invalide: 0,
          isChild: 0,
          parentIsole: 0,
          plus65ans: 1,
          veufVeuve: 0,
        },
      ],
    },
    revenusNetMensuel: 1300,
  }, {
    lieuResidence: 0,
    name: "Foyer fiscal type",
    nbCouple: 2,
    nbEnfants: 2,
    persons: {
      childs: [
        {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 0,
          invalide: 0,
          isChild: 1,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        }, {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 0,
          invalide: 0,
          isChild: 1,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        },
      ],
      parents: [
        {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 0,
          invalide: 0,
          isChild: 0,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        }, {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 1,
          invalide: 0,
          isChild: 0,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        },
      ],
    },
    revenusNetMensuel: 4500.25,
  }, {
    lieuResidence: 1,
    name: "Foyer fiscal type",
    nbCouple: 2,
    nbEnfants: 2,
    persons: {
      childs: [
        {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 0,
          invalide: 0,
          isChild: 1,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        }, {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 0,
          invalide: 0,
          isChild: 1,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        },
      ],
      parents: [
        {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 1,
          invalide: 0,
          isChild: 0,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        }, {
          ancienCombattant: 0,
          chargePartagee: 0,
          gender: 0,
          invalide: 0,
          isChild: 0,
          parentIsole: 0,
          plus65ans: 0,
          veufVeuve: 0,
        },
      ],
    },
    revenusNetMensuel: 4500.25,
  },
];
